apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pcs-data-service.fullname" . }}
  labels:
    {{- include "pcs-data-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pcs-data-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/ConfigEnv: {{ include (print $.Template.BasePath "/pcs-data-service_env.yaml") . | sha256sum }}
      labels:
        {{- include "pcs-data-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pcs-data-service.serviceAccountName" . }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: data-service
              containerPort: 8080
              protocol: TCP
          env:
            - name: AZ
              value: "{{ .Values.AZ }}"
          envFrom:
          - configMapRef:
              name: {{.Chart.Name}}
          - configMapRef:
              name: {{.Release.Namespace}}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 40
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

